openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  description: API для управления контактами
tags:
  - name: Contacts
    description: Операции с контактами
servers:
  - url: http://localhost:3000
  - url: https://contacts-app-ycri.onrender.com
paths:
  /contacts:
    get:
      $ref: './swagger/paths/contacts/get.yaml' # Роут для получения списка контактов
    post:
      $ref: './swagger/paths/contacts/post.yaml' # Роут для создания контакта
  /contacts/{contactId}:
    get:
      $ref: './swagger/paths/contacts/{id}/get.yaml' # Роут для получения контакта по ID
    patch:
      $ref: './swagger/paths/contacts/{id}/patch.yaml' # Роут для обновления контакта
    delete:
      $ref: './swagger/paths/contacts/{id}/delete.yaml' # Роут для удаления контакта
components:
  schemas:
    $ref: './swagger/components/schemas.yaml' # Ссылки на схемы сущностей
  responses:
    $ref: './swagger/components/responses.yaml' # Ссылки на стандартные ответы
  parameters:
    $ref: './swagger/components/parameters.yaml' # Ссылки на параметры запроса
